### PR TITLE
add multivisualization page

### PR DESCRIPTION
**Pull request by eperedo**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/860r99w63

### :memo: Implementation

Some visualizations cannot be render because plugin limitations https://dhis2.atlassian.net/browse/DHIS2-15592

### :video_camera: Screenshots/Screen capture

[Multi-Visualization-App.webm](https://github.com/EyeSeeTea/d2-multi-visualization/assets/461124/40cf9b21-f85a-4169-8aa1-13c3c276bb4b)

### :fire: Notes to the tester

I already install the app on DEV, but if you want to try in a different server please run `yarn install` and `yarn build` to generate the zip file.

### CODE REVIEW

**Comment by MiquelAdell** [comment]
I have tested it in our dev and widp dev and sent it to the client for review. As the code works I'll merge the pull request.

I had an issue while testing though. How could I, with this app, run it as it's own server? I tried using yarn start and it *seems* to work but it does not load.
Screenshot 2023-10-06 at 15 02 38
Screenshot 2023-10-06 at 15 02 44

Is there something I'm missing?

Thanks!

**Comment by eperedo** [comment]
are you getting any errors logged to the console?

**Comment by MiquelAdell** [comment]
Yes, it loads a bunch of things and when it finishes I get this:
Screenshot 2023-10-06 at 16 01 29
Screenshot 2023-10-06 at 16 01 35

**Comment by eperedo** [comment]
are you testing against dev, right?

Looks like it's not possible to load the `chart` and `reporttable` plugins from localhost (see in the network these requests are returning 302 status).

Not a problem when you test against a local instance or as an installed app. I'm going to add all the plugins in the repo so we can test from any environment. I did not want to do this in first place because plugins are very heavy but looks like the only solution.

**Comment by MiquelAdell** [comment]
@eperedo maybe that's the solution, not sure. Anyway I've recorded what happens to me just so you have it as a reference

https://github.com/EyeSeeTea/d2-multi-visualization/assets/4996457/cc1bed40-e8f1-4120-8eed-6660fd533343

**Pull request merged**
